/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.example.entity.user.User;

public class App {

    public static void main(String[] args) {
        ObjectMapper mapper = new ObjectMapper();
        try {
            System.out.println(mapper.writerWithDefaultPrettyPrinter()
                    .writeValueAsString(new User("Ivan", "Shalaiev")));
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    }
}
